# Generated by Django 5.2.7 on 2026-09-21 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cheque_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='refund_preference',
            field=models.CharField(choices=[('lumina', 'Deposit to LuminaBank Checking'), ('external', 'Direct Deposit to External Bank Account')], default='lumina', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('card', 'Card Payment'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque / Check')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='completed', max_length=20),
        ),
        migrations.CreateModel(
            name='LinkedBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('routing_number', models.CharField(max_length=9)),
                ('account_number', models.CharField(max_length=17)),
                ('account_number_last4', models.CharField(editable=False, max_length=4)),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings')], default='checking', max_length=20)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_banks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Linked Bank Account',
                'verbose_name_plural': 'Linked Bank Accounts',
            },
        ),
        migrations.CreateModel(
            name='FinancialAidDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('school_name', models.CharField(default='Partner University', max_length=200)),
                ('term', models.CharField(blank=True, help_text='e.g. Fall 2026', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('destination', models.CharField(choices=[('lumina', 'LuminaBank Checking'), ('external', 'External Bank Account')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aid_disbursements', to=settings.AUTH_USER_MODEL)),
                ('external_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aid_received', to='core.linkedbankaccount')),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_external_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by', to='core.linkedbankaccount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='linked_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to='core.linkedbankaccount'),
        ),
    ]
